# Generated by Django 4.2 on 2026-03-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='from_code',
            new_name='from_coded',
        ),
    ]
