# Generated by Django 4.2 on 2026-03-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_from_code_flight_from_coded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='from_coded',
        ),
    ]
