# Generated by Django 4.2 on 2026-03-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_flight_from_coded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
