# Generated by Django 4.2 on 2026-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_testimonial_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='from_code',
            field=models.CharField(default='MAA', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
