# Generated by Django 4.2 on 2026-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_ref',
            field=models.CharField(default='BK-000000', max_length=20),
            preserve_default=False,
        ),
    ]
