# Generated by Django 4.2 on 2026-03-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_booking_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=10)),
                ('arrival_time', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=20)),
                ('train_type', models.CharField(max_length=50)),
                ('classes', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
