# Generated by Django 4.2 on 2026-03-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(max_length=20)),
                ('amenities', models.TextField()),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
