# Generated by Django 4.2 on 2026-03-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='movies/')),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('showtimes', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
